### ISSUE TITLE
Can't scroll past first page of Waystone list

### ISSUE THREAD

**Issue by SmallSansSerif** [PolymerPorts/FabricWaystones#2]
Multiple users on our 1.18.1 Fabric server have reported that they can't get past the first page of the Waystone list.

Version of plugin:
wraith-waystones-2.4.1-polymerport.2.jar (we are running 1.18.1 to support a modpack)

![waystone_bug1](https://user-images.githubusercontent.com/4984139/161281886-21556916-1ac6-4d6b-9745-0d141058d472.png)

**Comment by Patbox** [comment]
Fixed on latest (2.5.0-polymerport.1 for 1.18.2)
